### ISSUE TITLE
errors in log file

### ISSUE THREAD

**Issue by johanlott** [Geta/404handler#85]
Since upgrading BVNetwork.EPi404 to version 11.1.0 we´re getting lots of errors in our log.

ERROR BVNetwork.NotFound.Core.Data.DataAccessBaseEx: An error occured while logging a 404 handler error. Ex:System.Data.SqlClient.SqlException (0x80131904): The parameterized query '(@requested datetime,@referer nvarchar(4000),@oldurl nvarchar(40' expects the parameter '@referer', which was not supplied.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at BVNetwork.NotFound.Core.Data.DataAccessBaseEx.<>c__DisplayClass14_0.<LogRequestToDb>b__0()
ClientConnectionId:5a699dc9-86f4-4a4f-afd1-1d113ad1c18f
Error Number:8178,State:1,Class:16

The module seems to work despite the error messages but the log file is growing...
Any ideas?

Regards, Johan

**Comment by marisks** [comment]
Could you upgrade to 11.1.5? There are several bugs fixed in latest versions.
But I haven't noticed anything you have.

**Comment by johanlott** [comment]
We have upgraded to version 11.1.5, unfortunately, it did not help, still getting these errors in the log file.

**Comment by davidelias0** [comment]
We are on 11.1.5 also and are receiving this error.  We just did a full upgrade and as far as we can tell this just took all of our sites down.

**Comment by marisks** [comment]
Do you have a description of steps how to reproduce it?

@davidelias0 how did the 404 handler took all your sites down?

**Comment by marisks** [comment]
I found the issue and made the fix, but I am not able to publish packages yet as nuget.episerver.com is not working properly. Will upload new packages as soon as Episerver will fix their site.

**Comment by johanlott** [comment]
Sounds good @marisks !

**Comment by thomaswolff** [comment]
@marisks Which version of the Nuget Package is the fix included in?
